### PR TITLE
Closes the transaction on GrpcCommunicator error

### LINKED ISSUE #62: Transaction is not closed on the client when it fails on the server
## Description
When a transaction fails with an exception (on the server), it is not closed on the client.

## Environment

1. OS (where Grakn server runs): Mac OS 10.14.6
2. Grakn version (and platform): Grakn Core 1.5.9
3. Grakn client-nodejs version: client-nodejs 1.5.5
4. Node.js version: 11.15.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open a client, session and transaction
2. run `await transaction.query('match typo');`
3. Receive an exception (expectedly)
4. run `await transaction.query('match whatever');`

## Expected Output
Receive an exception saying that the transaction has already been closed.

## Actual Output
Nothing happens

### PR DESCRIPTION
**Pull request by sorsaffari**
## What is the goal of this PR?
When the transaction fails, it is now marked as closed within the client.

## What are the changes implemented in this PR?
resolves #62
- adds dependencies:
  - 1. `properties-reader`: for reading `.properties` files
  - 2. `jasmine-reporters`: for better test reporting
- `end`s the `GrpcCommunicator` on `error` + test
- before starting the Grakn Server in `startGraknServer` checks if one is already running
- uses `execSync` for running `grakn` commands within, since they need to run synchronously anyways
- make `/tmp` writable as when running console commands a history file is written into the `/tmp` directory

### CODE REVIEW

**Comment by marco-scoppetta** [comment]
@sorsaffari can we add a test [here](https://github.com/graknlabs/client-nodejs/blob/master/tests/service/session/transaction/GraknTx.test.js) that runs a syntactically wrong query and then tries to re-use the transaction -> we should expect a "Transaction is already closed" exception

**Comment by sorsaffari** [comment]
@marco-scoppetta added the test and update the PR description

File: tests/support/GraknTestEnvironment.js [hunk 1]
```diff
@@ -122,12 +102,24 @@ module.exports = {
...
+        const GRPC_PORT = 'grpc.port';
+        const uri = `${graknProperties.get(SERVER_HOST_NAME)}:${graknProperties.get(GRPC_PORT)}`;
+
+        try {
+            childProcess.execSync(`curl ${uri}`);
+            throw new Error('Grakn Server is already running. Stop it before running the integration tests');            
+        } catch (error) {
+            execGraknCommand(getServerCommand('start'));
+            execGraknCommand(getLoadGraqlCommand(path.resolve('.', 'tests/support/basic-genealogy.gql'), 'gene'))
+        }
```
Comment (marco-scoppetta) [inline tests/support/GraknTestEnvironment.js]: minor, but what about:
```
function isGraknRunning(){
     try {
            childProcess.execSync(`curl ${uri}`);
            return true;          
        } catch (error) {
             return false;
        }
}
```
so that we can have:
```
   if(!isGraknRunning()){
           execGraknCommand(getServerCommand('start'));
            execGraknCommand(getLoadGraqlCommand(path.resolve('.', 'tests/support/basic-genealogy.gql'), 'gene'))
   }
```

File: tests/service/session/transaction/GraknTx.test.js [hunk 2]
```diff
@@ -91,4 +94,12 @@ describe("Transaction methods", () => {
     await env.graknClient.keyspaces().delete('computecentralityks');
   });
 
+  it("transaction closes on error", async () => {
+    const localSession = await env.sessionForKeyspace('computecentralityks');
+    let localTx = await localSession.transaction().write();
+    await localTx.query("invalid query").catch(() => console.log('query expectedly failed.'));
```
Comment (marco-scoppetta) [inline tests/service/session/transaction/GraknTx.test.js]: do we need the catch with console log?

File: tests/support/GraknTestEnvironment.js [hunk 3]
```diff
@@ -105,6 +105,7 @@ module.exports = {
         
         // fix permissions to not get EACCES
         fs.chmodSync(graknExecutablePath, 0o755);
+        // make `/tmp` writable as running console commands creates a file in there
```
Comment (marco-scoppetta) [inline tests/support/GraknTestEnvironment.js]: 👍

File: tests/support/GraknTestEnvironment.js (hunk 1 above)
Comment (sorsaffari) [reply tests/support/GraknTestEnvironment.js]: yeah, that's better 👍

File: tests/service/session/transaction/GraknTx.test.js (hunk 2 above)
Comment (sorsaffari) [reply tests/service/session/transaction/GraknTx.test.js]: we do need to have the `catch`, but the `console.log()` isn't necessary. I'll remove the logging
